# Generated by Django 4.2.6 on 2024-03-28 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('max_temp', models.IntegerField()),
                ('min_temp', models.IntegerField()),
                ('max_soil_temp', models.IntegerField()),
                ('min_soil_temp', models.IntegerField()),
                ('max_moisture', models.IntegerField()),
                ('min_moisture', models.IntegerField()),
                ('max_water_ph', models.DecimalField(decimal_places=2, max_digits=3)),
                ('min_water_ph', models.DecimalField(decimal_places=2, max_digits=3)),
                ('max_light_intensity', models.IntegerField()),
                ('min_light_intensity', models.IntegerField()),
                ('max_humidity', models.IntegerField()),
                ('min_humidity', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CurrentStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iot_set_flag', models.BooleanField(default=False)),
                ('water_ph', models.DecimalField(decimal_places=2, max_digits=3)),
                ('light_intensity', models.IntegerField()),
                ('humidity', models.IntegerField()),
                ('soil_temp', models.IntegerField()),
                ('moisture', models.IntegerField()),
                ('temperature', models.IntegerField()),
                ('water_level', models.IntegerField()),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MidApp.plant')),
            ],
        ),
    ]
