# Generated by Django 4.2.6 on 2024-03-29 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MidApp', '0002_alter_currentstatus_humidity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='currentstatus',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
    ]
