# Generated by Django 4.2.6 on 2024-03-29 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MidApp', '0003_currentstatus_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currentstatus',
            name='timestamp',
        ),
    ]
