# Generated by Django 4.2.6 on 2024-03-29 11:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('MidApp', '0004_remove_currentstatus_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='currentstatus',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
    ]
