# Generated by Django 4.2.6 on 2024-03-29 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MidApp', '0005_currentstatus_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='light_schedule',
            field=models.CharField(default='00:00-13:00', max_length=25),
        ),
    ]
