# Generated by Django 4.2.6 on 2024-04-08 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MidApp', '0006_plant_light_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentstatus',
            name='water_ph',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
