# Generated by Django 4.2.6 on 2024-04-16 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MidApp', '0007_alter_currentstatus_water_ph'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.BinaryField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='plant',
            name='max_water_ph',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='plant',
            name='min_water_ph',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
