# Generated by Django 4.2.6 on 2024-04-16 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MidApp', '0008_footage_alter_plant_max_water_ph_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footage',
            name='image',
            field=models.TextField(),
        ),
    ]
