# Generated by Django 4.2.6 on 2024-04-18 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MidApp', '0010_alter_footage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footage',
            name='image',
            field=models.TextField(),
        ),
    ]
